### ISSUE TITLE
Deployment fails on Kubernetes 1.6.2 deployed on CentOS

### ISSUE THREAD

**Issue by carlosedp** [nanit/kubernetes-graphite-cluster#12]
I have a Kube 1.6.2 deployed over CentOS VMs using Kubeadm.

When I tried to deploy the carbon/graphite cluster, I got the following errors in the Make progress:

```
...
...
Step 22 : RUN chmod 0664 /opt/graphite/storage/graphite.db
 ---> Running in b4297ad8b242
 ---> e468c1e48708
Removing intermediate container b4297ad8b242
Step 23 : RUN cp /src/graphite-web/webapp/manage.py /opt/graphite/webapp
 ---> Running in 8454921eed63
 ---> fc42a56abfc4
Removing intermediate container 8454921eed63
Step 24 : RUN cd /opt/graphite/webapp/ && python manage.py migrate --run-syncdb --noinput
 ---> Running in b01ad861d148
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/settings.py", line 153, in <module>
    from graphite.local_settings import *  # noqa
  File "/opt/graphite/webapp/graphite/local_settings.py", line 246
    CLUSTER_SERVERS = [@@GRAPHITE_NODES@@]
                       ^
SyntaxError: invalid syntax
The command '/bin/sh -c cd /opt/graphite/webapp/ && python manage.py migrate --run-syncdb --noinput' returned a non-zero code: 1
make: *** [docker-graphite-master] Error 1 
```

This happens in the carbon-relay pod logs:

NAMESPACE     NAME                                          READY     STATUS              RESTARTS   AGE
default       carbon-relay-2782403225-cvtk3                 0/1       CrashLoopBackOff    5          23m
default       carbon-relay-2782403225-xf7nk                 0/1       CrashLoopBackOff    9          23m
default       carbon-relay-2782403225-zmlf5                 0/1       ErrImagePull        0          23m

Log:

```
kubectl logs carbon-relay-2782403225-xf7nk

+ /set-cluster-nodes.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to kubernetes port 443: Connection refused
+ exec /opt/graphite/bin/carbon-relay.py --debug --logdir=/var/log/carbon start
Traceback (most recent call last):
Starting carbon-relay (instance a)
  File "/opt/graphite/bin/carbon-relay.py", line 32, in <module>
    run_twistd_plugin(__file__)
  File "/opt/graphite/lib/carbon/util.py", line 96, in run_twistd_plugin
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 436, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/opt/graphite/lib/twisted/plugins/carbon_relay_plugin.py", line 21, in makeService
    return service.createRelayService(options)
  File "/opt/graphite/lib/carbon/service.py", line 135, in createRelayService
    setupPipeline(['relay'], root_service, settings)
  File "/opt/graphite/lib/carbon/service.py", line 86, in setupPipeline
    setupRelayProcessor(root_service, settings)
  File "/opt/graphite/lib/carbon/service.py", line 175, in setupRelayProcessor
    for destination in util.parseDestinations(settings.DESTINATIONS):
  File "/opt/graphite/lib/carbon/util.py", line 121, in parseDestinations
    return [parseDestination(dest_string) for dest_string in destination_strings]
  File "/opt/graphite/lib/carbon/util.py", line 117, in parseDestination
    return server, int(port), instance
ValueError: invalid literal for int() with base 10: '@@GRAPHITE_NODES@@'


```

**Comment by erez-rabih** [comment]
Hi @carlosedp thanks for reporting this
I just merged https://github.com/nanit/kubernetes-graphite-cluster/pull/13 which supposed to fix your issue
Can you please check and report back to this issue?

**Comment by erez-rabih** [comment]
@carlosedp I'm closing this for now due to inactivity.

If you still have the issue please re-open it.
